[package]
name = "vanity_sniper"
version = "0.1.0"
edition = "2021"

[dependencies]
clearscreen = "2.0.0"
colored = "2.0.0"
dotenv = "0.15.0"
serde = "1.0.152"
serde_json = "1.0.93"
surf = "2.3.2"
tokio = { version = "1.26.0", features = ["full"] }
